# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default  # aapka self-hosted agent

steps:
# Step 1: Use compatible Node.js
- task: UseNode@1
  inputs:
    version: '20.x'

# Step 2: Install Angular CLI and app dependencies
- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'Install dependencies'

# Step 3: Build Angular app
- script: |
    ng build --configuration=production
  displayName: 'Build Angular App'

# Step 4: Deploy to Azure VM via SSH
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'Azure-to-vm'   # 👈 yeh service connection ka naam hai
    sourceFolder: 'dist/simple-angular-app'      # 👈 isko replace karo Angular build folder name se
    contents: '**'
    targetFolder: '/var/www/html/angular-app'  # 👈 yeh Azure VM ka nginx root folder hai
    cleanTargetFolder: true
    overwrite: true
